# Generated by Django 5.0.14 on 2026-07-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FailedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255, unique=True)),
                ("task_name", models.CharField(max_length=255)),
                ("payload", models.JSONField()),
                ("error_message", models.TextField()),
                ("failed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
